apiVersion: v1
kind: Pod
metadata:
  name: azure-service-app
  labels:
    app: azure-service-app
spec:
  replicas: 5
  containers:
  - name: spring-azure-service
    image: mdbodatrainer/spring-azure-service:latest
    ports:
    - containerPort: 80